name: Sync specific txt files

on:
  schedule:
    # 每天触发一次工作流 (每天午夜 00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3  # 使用 v3 版本

    - name: Download txt files from upstream
      run: |
        # 拉取 doh-vpn-proxy-bypass.txt 文件
        curl -o doh-vpn-proxy-bypass.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass.txt
        # 拉取 ultimate.txt 文件
        curl -o ultimate.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
        # 拉取 popupads.txt 文件
        curl -o popupads.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads.txt
        # 拉取 tif.txt 文件
        curl -o tif.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt

    - name: Modify the txt files
      run: |
        for file in doh-vpn-proxy-bypass.txt ultimate.txt popupads.txt; do
          # 添加 payload 到文件开头
          echo "payload:" | cat - $file > temp && mv temp $file
          # 替换 * 为 "  - +"
          sed -i 's/\*/  - +/g' $file
        done

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        # 只有在有更改时才提交
        git diff --quiet || (git add . && git commit -m 'Update txt files with payload and replacement')

    - name: Push changes
      run: |
        git push origin main
      if: success()  # 只有在有更改提交时才推送
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
