name: Sync specific txt files

on:
  schedule:
    # 每天北京时间 8:00 和 20:00 触发工作流
    - cron: '0 0,12 * * *'
  workflow_dispatch:
    # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3  # 使用 v3 版本

    - name: Download txt files from upstream
      run: |
        # 拉取 doh-vpn-proxy-bypass.txt 文件
        curl -o doh-vpn-proxy-bypass.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass.txt
        # 拉取 ultimate.txt 文件
        curl -o ultimate.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
        # 拉取 popupads.txt 文件
        curl -o popupads.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads.txt
        # 拉取 tif.txt 文件
        curl -o tif.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt
        # 拉取 doh.txt 文件
        curl -o doh.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/ips/doh.txt

    - name: Modify txt files
      run: |
        for file in doh-vpn-proxy-bypass.txt ultimate.txt popupads.txt tif.txt doh.txt; do
          # 添加 payload 到文件开头
          echo "payload:" | cat - $file > temp && mv temp $file
          # 为 doh.txt 特殊处理，前加 "  - "，后加 "/32"
          if [[ "$file" == "doh.txt" ]]; then
            sed -i 's/^/  - /; s/$/\/32/' $file
          else
            # 替换 * 为 "  - +" 用于其他文件
            sed -i 's/\*/  - +/g' $file
          fi
        done

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        # 强制添加 doh.txt 文件并提交
        git add doh.txt
        git add .
        git diff --cached --quiet || git commit -m 'Update txt files with payload and replacement'

    - name: Push changes
      run: |
        git push origin main
      if: success()  # 只有在有更改提交时才推送
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  workflowcleanup:
    name: Cleanup old workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1  # 只保留一天内的工作流运行记录
          keep_minimum_runs: 1  # 至少保留一次工作流运行记录
    needs: sync  # 等待 sync 任务完成后执行
